[package]
name = "rawrscope"
version = "0.1.0"
authors = ["rytone <rytonemail@gmail.com>"]
edition = "2018"

[dependencies]
hound = "3.4.0"
ron = "0.5.1"
serde = { version = "1.0.97", features = ["derive"] }
snafu = "0.4.1"
