[package]
name = "rawrscope"
version = "0.1.0"
authors = ["rytone <rytonemail@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
clap = "2.33.0"
cpal = "0.10.0"
crossbeam-channel = "0.3.8"
failure = "0.1.5"
fern = { version = "0.5.8", features = ["colored"] }
hound = "3.4.0"
log = "0.4.7"
parking_lot = "0.9.0"
ron = "0.5.1"
sample = "0.10.0"
samplerate = { git = "https://github.com/rytone/rust-samplerate" }
serde = { version = "1.0.97", features = ["derive"] }
snafu = "0.4.1"
tinyfiledialogs = "3.3.6"
toml = "0.5.1"

[profile.release]
debug = true
