[package]
name = "rawrscope"
version = "0.1.0"
authors = ["rytone <rytonemail@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.97", features = ["derive"] }
serde_yaml = "0.8.9"
snafu = "0.4.1"
