[package]
name = "rawrscope"
version = "0.1.0"
authors = ["rytone <rytonemail@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
fern = { version = "0.5.8", features = ["colored"] }
hound = "3.4.0"
log = "0.4.7"
ron = "0.5.1"
sample = "0.10.0"
serde = { version = "1.0.97", features = ["derive"] }
snafu = "0.4.1"
