cargo-features = ["named-profiles"]

[package]
name = "rawrscope"
version = "0.1.0"
authors = ["rytone <max@ryt.one>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
ambassador = "0.2.1"
bitflags = "1.2.1"
clap = "2.33.0"
cpal = "0.11.0"
crossbeam-channel = "0.4.2"
derivative = "1.0.3"
directories = "2.0.2"
fern = { version = "0.5.8", features = ["colored"] }
git-version = "0.3.4"
hound = "3.4.0"
imgui = "0.3.0"
imgui-winit-support = { version = "0.3.0", default-features = false, features = ["winit-20"] }
imgui-wgpu = { git = "https://github.com/Yatekii/imgui-wgpu-rs" }
log = "0.4.7"
parking_lot = "0.10.0"
rayon = { git = "https://github.com/nikomatsakis/rayon", branch = "latch-target-thread" }
sample = "0.10.0"
samplerate = "0.2.1"
serde = { version = "1.0.104", features = ["derive"] }
serde_yaml = "0.8.11"
snafu = "0.6.2"
tinyfiledialogs = "3.3.6"
toml = "0.5.6"
ultraviolet = "0.4.5"
vk-shader-macros = "0.2.2"
winit = "0.21.0"
wgpu = "0.4.0"

[patch.crates-io]
libsamplerate-sys = { git = "https://github.com/rytone/libsamplerate-sys" }
shaderc = { git = "https://github.com/google/shaderc-rs" }

[profile.release]
debug = true

[profile.deploy]
inherits = "release"
debug = false
opt-level = 3
lto = "fat"
