cargo-features = ["named-profiles"]

[package]
name = "rawrscope"
version = "0.1.0"
authors = ["rytone <rytonemail@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
clap = "2.33.0"
cpal = "0.10.0"
crossbeam-channel = "0.3.8"
derivative = "1.0.3"
directories = "2.0.2"
failure = "0.1.5"
fern = { version = "0.5.8", features = ["colored"] }
hound = "3.4.0"
imgui = "0.2.1"
imgui-winit-support = { version = "0.2.1", default-features = false, features = ["winit-20"] }
imgui-wgpu = { git = "https://github.com/Yatekii/imgui-wgpu-rs" }
log = "0.4.7"
parking_lot = "0.9.0"
sample = "0.10.0"
samplerate = "0.2.1"
serde = { version = "1.0.97", features = ["derive"] }
serde_yaml = "0.8.11"
snafu = "0.4.1"
tinyfiledialogs = "3.3.6"
toml = "0.5.1"
winit = "0.20.0-alpha4"
wgpu = "0.4.0"

[patch.crates-io]
libsamplerate-sys = { git = "https://github.com/rytone/libsamplerate-sys" }

[profile.release]
debug = true

[profile.deploy]
inherits = "release"
debug = false
opt-level = 3
lto = true
