name: Build and test
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
